version: "3.4"

services:
  client:
    build: .
    container_name: vue-todo
    ports:
      - "18080:8080"
    expose:
      - "18080"
    volumes:
      - .:/app
    tty: true
    stdin_open: true